export { default as pipe } from './pipe'
export { default as compose } from './compose'
export { default as curry } from './curry'
export { default as trace } from './trace'
export { default as map } from './map'
